<?php
/**
 * 404 Monitor Settings Module
 * 
 * @since 2.1
 */

if (class_exists('SL_Module')) {

class SL_FofsSettings extends SL_Module {
	
	static function get_parent_module() { return 'fofs'; }
	static function get_child_order() { return 20; }
	static function is_independent_module() { return false; }
	
	static function get_module_title() { return __('404 Monitor Settings', 'seolat-tool-plus'); }
	function get_module_subtitle() { return __('Settings', 'seolat-tool-plus'); }
	function get_settings_key() { return '404s'; }
	
	function get_default_settings() {
		return array(
			  'exceptions' => "*/favicon.ico\n*/apple-touch-icon.png\n*/pingserver.php\n*/xmlrpc.php"
			, 'max_log_size' => 100
			, 'log_enabled' => $this->flush_setting('log_hits', true, 'settings')
			, 'restrict_logging' => true
			, 'log_spiders' => true
			, 'log_errors_with_referers' => true
		);
	}
	
	function init() {
		add_filter('sl_get_setting-404s-max_log_size', array('lat_string', 'to_int'));
	}
	
	function admin_page_contents() {

		$this->admin_form_start();
		$this->checkbox('log_enabled', __('Continue monitoring for new 404 errors', 'seolat-tool-plus'), __('Monitoring Settings', 'seolat-tool-plus'));
		$this->checkboxes(array(
			  'restrict_logging' => __('Only log these types of 404 errors:', 'seolat-tool-plus')
			, 'log_spiders' => array('description' => __('404s generated by search engine spiders', 'seolat-tool-plus'), 'indent' => true)
			, 'log_errors_with_referers' => array('description' => __('404s with referring URLs', 'seolat-tool-plus'), 'indent' => true)
		), __('Log Restrictions', 'seolat-tool-plus'));
		$this->textbox('max_log_size', __('Maximum Log Entries', 'seolat-tool-plus'), $this->get_default_setting('max_log_size'));
		$this->textarea('exceptions', __('URLs to Ignore', 'seolat-tool-plus') . '<br /><small><em>' . __('(Use * as wildcard)', 'seolat-tool-plus') . '</em></small>', 15);
		$this->admin_form_end();
	}
}

}
?>